### ISSUE TITLE
Zoom overlay sits behind Docsaurus nav bar

### ISSUE THREAD

**Issue by nomicode** [gabrielcsapo/docusaurus-plugin-image-zoom#7]
When I added your plugin to my site, I noticed that the zoom overlay appears behind the Docusaurus nav bar (which is set to `z-index: 200`). I was able to fix this issue with the following in my `custom.css`:

```css
.medium-zoom-overlay,
.medium-zoom-image {
  z-index: 9999;
}
```

Perhaps it would be worthwhile to include this by default with your plugin?
